In [8]:
import os
def createJsonfile(name,data):
    data_json = {"values": data}
    path = "E:\\unity_learn\\unity_project1\\read_webRequest_produce3dimage\\Assets\\data"
    filename = name;
    comp_path = os.path.join(path,filename)
# Serialize the dictionary to a JSON string and save it to a file
    with open(comp_path, 'w') as f:
        json.dump(data_json, f)

# Deserialize the JSON string from the file back into a dictionary
    with open(comp_path, 'r') as f:
        loaded_json = json.load(f)
        print("Data content of the JSON file and its name:",name, loaded_json)


In [9]:
import numpy as np
import json
import os

for i in range(1,4):
    
    if i==1:
        name = f"array{i}djson.json"
        data = np.arange(1,4).astype(float).reshape((1,-1)).tolist()
        print("if data is 1d then , data:",data)
        createJsonfile(name,data)
        
    if i ==2:
        name = f"array{i}djson.json"
        data = np.arange(1, 10).astype(float).reshape((3, 3)).tolist()
        createJsonfile(name,data)
        
    if i==3:
        name = f"array{i}djson.json"
        data = np.arange(1, 31).astype(float).reshape((5, 2, 3)).tolist()
        createJsonfile(name,data)
        

        
    


# Create a NumPy array and convert it to a Python list





# Create a dictionary with the key "values" and the list as its value


if data is 1d then , data: [[1.0, 2.0, 3.0]]
Data content of the JSON file and its name: array1djson.json {'values': [[1.0, 2.0, 3.0]]}
Data content of the JSON file and its name: array2djson.json {'values': [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]}
Data content of the JSON file and its name: array3djson.json {'values': [[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]], [[13.0, 14.0, 15.0], [16.0, 17.0, 18.0]], [[19.0, 20.0, 21.0], [22.0, 23.0, 24.0]], [[25.0, 26.0, 27.0], [28.0, 29.0, 30.0]]]}


In [53]:
for i in range(4):
    filename = f"name{i}.txt"
    print(filename)

name0.txt
name1.txt
name2.txt
name3.txt


In [49]:
import numpy as np
import json
# data = np.arange(1,3);
data = np.arange(1,10);
data =  data.astype(float)
data = data.reshape((3,3))
# print(data)
data = data.tolist()
print("type and list of data :",type(data[0][0]),data)
for val in data:
    print(val)

datajson = {"values":data}  
# datajson1 = json.dumps(datajson)
print("json format: ", datajson1)
with open('jsonfile.json','w') as f:
    json.dump(datajson,f)
#     f.write(datajson1)

    
with open('jsonfile.json','r') as f1:
    datajson = json.load(f1)
    print("data content of the json file:",datajson)
    print(type(datajson))
#     i=0
    for val in datajson:
        print(val)
        
        

type and list of data : <class 'float'> [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
[1.0, 2.0, 3.0]
[4.0, 5.0, 6.0]
[7.0, 8.0, 9.0]
json format:  {"values": [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]}
data content of the json file: {'values': [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]}
<class 'dict'>
values


In [1]:
""" for testing the json file similar to the  processed yeast file."""
import json 
import numpy as np
import os
# arr1d = np.random.randint(15,5,5)
# listarr=np.arange(1,4,dtype=float)
# print("type of the data : ",np.dtype(listarr[0]))
# arr1d = listarr.reshape((3,3,3))
#  this is for 2d array json file.
listarr=np.arange(1,10)
arr1d = listarr.reshape((3,3))
print(arr1d)
arr1d = listarr
# print(arr1d)
arr1d = arr1d.tolist()
print("data list:",arr1d)
arrdata ={"values":arr1d}

# jsondata = arrdata
jsondata = json.dumps(arrdata)  
print("json data \n",jsondata)
path = "E:\\unity_learn\\unity_project1\\read_webRequest_produce3dimage\\Assets\\data"
filename = "trial2d.json"
comp_path = os.path.join(path,filename)
with open(comp_path,'w') as f1:
    # f1.write(jsondata)
    json.dump(jsondata,f1)

# with open("examp1.json",'w') as file:
#     json.dump(arrdata,file)


with open(comp_path,'r') as file1:
    dataserialization = json.load(file1)
    print(dataserialization)
    # data = json.load()


[[1 2 3]
 [4 5 6]
 [7 8 9]]
data list: [1, 2, 3, 4, 5, 6, 7, 8, 9]
json data 
 {"values": [1, 2, 3, 4, 5, 6, 7, 8, 9]}
{"values": [1, 2, 3, 4, 5, 6, 7, 8, 9]}


In [ ]:
# import json
with open('fact.json', 'r+') as frd:
    print(frd.read())
#     filecontent = frd.read()
#     jsonload = json.load(frd)
#     print(jsonload)

In [ ]:
# print(filecontent)
# if we want to dump any object in json format just use --> json.dumps(x)  --> x is any object.
# understand and summarize the different technique of reading and writing from/into file,with
# different file format csv,excel,text,.dat, and json also.

In [ ]:
import json
import numpy as np
with open('pdata_217071456512135513.json','r') as fpdata:
# with open('pdata_617060994055166562.json','r') as fpdata:
    fdata = fpdata.read()
    # Parse the JSON string into a Python dictionary
    data_dict = json.loads(fdata)

# Access the "values" key and print a slice
    print(data_dict["values"][0][1][0:10])
    data_row = data_dict["values"][0][1][0:10]
    data_row = np.array(data_row)
    print("\n size of the data_row:\n",data_row.shape,"\n length: ",len(data_row))

In [ ]:
import json
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
# Load JSON data
with open('pdata_217071456512135513.json','r') as fpdata:
# with open('pdata_617060994055166562.json','r') as fpdata:
    fdata = fpdata.read()
    filename = "justsee"
    data = json.loads(fdata)
    data = np.array(data["values"])
array_3d = data[0:100,0:100,0:100]
print("shape of the array is :----------------> \n",array_3d.shape)
# Find non-zero values
nonzero_indices = np.nonzero(array_3d)
# Create mesh grid for non-zero values
X, Y, Z = np.meshgrid(nonzero_indices[0], nonzero_indices[1], nonzero_indices[2])
# Create figure and axis
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
# Plot surface for non-zero values
ax.plot(X, Y, Z,color='r', marker='.')  # You can also use plot_surface() if you want a surface plot
# Set labels
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

# Show plot
plt.show()


In [ ]:
import numpy as np
from interactive_plot3dmodule import plot3d_yeastSegmentdata
with open('pdata_217071456512135513.json','r') as fpdata:
# with open('pdata_617060994055166562.json','r') as fpdata:
    fdata = fpdata.read()
    filename = "justsee"
    data = json.loads(fdata)
    data = np.array(data["values"])
    data = data[0:100,0:100,0:100]
    print("\n size of the given data : array_3d :\n ",data.shape)
    plot3d_yeastSegmentdata(data,filename)
    # Parse the JSON string into a Python dictionary
#     data_dict = json.loads(fdata)

# Access the "values" key and print a slice
#     print(data_dict[2][0:1][0:10])
#     data_row = data_dict[0][1][0:10]
#     data_row = np.array(data_row)
#     print("\n size of the data_row:\n",data_row.shape,"\n length: ",len(data_row))

In [ ]:
data.shape 

In [ ]:

wdata = data[0:20,0:20,0:20]

In [ ]:
data.shape

In [ ]:
import  json
with open("jsonfile.json",'w') as fjsn:
#     fdata = fjswritableit
    json.dump(data,fjsn)
    
with open("jsonfile.json") as f:
    fdata = f.read()
    dataread = json.loads(fdata)
    print(dataread)
    dataread = np.array(dataread)
    print("size is 20x20x20 : ",dataread.shape)

In [ ]:
import json

# Example data to write to the JSON file
data_to_write = {
    "name": "John",
    "age": 30,
    "city": "New York"
}

# Writing to a JSON file
with open('data.json', 'w') as json_file:
    json.dump(data_to_write, json_file)

# Reading from a JSON file
with open('data.json', 'r') as json_file:
    data_read = json.load(json_file)

print("Data read from JSON file:", data_read)


In [ ]:
for i in range(3,7,1):
    print(i)
    %mkdir "week"{i}
    
    
    